---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2026
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
name: CI
"on":
  push:
  pull_request:
permissions: read-all
jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      scripts: ${{ steps.filter.outputs.scripts }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
        with:
          persist-credentials: false
      # yamllint disable rule:line-length
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # 4.0.1
        # yamllint enable rule:line-length
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            scripts:
              - '**.sh'
              - '.shellspec'
              - 'spec/**'
              - 'Makefile'
  check-shellspec:
    name: Run BDD shell specs
    needs: changes
    if: needs.changes.outputs.scripts == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
        with:
          persist-credentials: false
      - name: Install ShellSpec
        run: >-
          curl -fsSL
          https://github.com/shellspec/shellspec/releases/latest/download/shellspec-dist.tar.gz
          | tar -xz -C ..
      - name: Run ShellSpec
        shell: 'script -q -e -c "bash {0}"'
        run: ../shellspec/shellspec --profile --xtrace
